/**
 * WTM — Master Experience Database v3
 * ─────────────────────────────────────────────────────────────────────────────
 * v3 changes from v2:
 *  • Tier colors: Amethyst (Rookie) / Emerald (Regular) / Ruby (Local)
 *  • Points NEVER expire
 *  • Points credit 48-72 hours after host marks experience completed
 *  • Cancellation policy added per experience
 *  • waiver_required + verification_level added per experience
 *  • preview_tier: allows lower tiers to see some higher-tier experiences
 *  • Prices rebalanced — blended average ~$165 (down from $250)
 *  • Favorites system added (user_favorites helper)
 *  • Redemption catalog rebuilt: 3 core (always) + 3 rotating (seasonal)
 *    — no single high-cost experience redeemable; discounts only on premium
 *    — universal caps on every redemption (per-member + global quarterly)
 *  • Spend never surfaces in user-facing copy
 *  • Installments: $500+ only
 *  • Free experiences: unlimited bookings, 0.25 QE capped at 25% annual
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORIES (7)
// ─────────────────────────────────────────────────────────────────────────────
const CATEGORIES = {
  dining:    { label:'Dining',       color:'#a855f7', icon_url:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=85' },
  offshore:  { label:'Offshore',     color:'#14b8a6', icon_url:'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=600&q=85' },
  arts:      { label:'Arts & Music', color:'#ec4899', icon_url:'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&q=85' },
  adventure: { label:'Adventure',    color:'#f59e0b', icon_url:'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=85' },
  wellness:  { label:'Wellness',     color:'#22c55e', icon_url:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=85' },
  outside:   { label:'Outside',      color:'#6366f1', icon_url:'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=85' },
  kids:      { label:'Kid-Friendly',         color:'#f59e0b', icon_url:'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?w=600&q=85' },
};

// ─────────────────────────────────────────────────────────────────────────────
// TIERS — Amethyst / Emerald / Ruby
// ─────────────────────────────────────────────────────────────────────────────
const TIERS = {
  rookie: {
    label:                  'Rookie',
    gem:                    'Amethyst',
    color:                  '#a855f7',
    gradient:               'linear-gradient(135deg,#c084fc,#a855f7,#7e22ce)',
    qe_min: 0,  qe_max: 6,
    points_mult:            1.00,
    discount_pct:           0,
    early_access_hours:     0,
    members_only_unlocked:  false,
    priority_sold_out:      false,
    ai_concierge:           false,
    human_concierge:        false,
    // Which tier's preview experiences this tier can see
    preview_of_tier:        'regular',
    preview_count:          3,
  },
  regular: {
    label:                  'Regular',
    gem:                    'Emerald',
    color:                  '#10b981',
    gradient:               'linear-gradient(135deg,#34d399,#10b981,#047857)',
    qe_min: 7,  qe_max: 17,
    points_mult:            1.05,
    discount_pct:           5,
    early_access_hours:     24,
    members_only_unlocked:  true,
    priority_sold_out:      false,
    ai_concierge:           true,
    human_concierge:        false,
    preview_of_tier:        'local',
    preview_count:          3,
  },
  local: {
    label:                  'Local',
    gem:                    'Ruby',
    color:                  '#e11d48',
    gradient:               'linear-gradient(135deg,#fb7185,#e11d48,#9f1239)',
    qe_min: 18, qe_max: Infinity,
    points_mult:            1.10,
    discount_pct:           10,
    early_access_hours:     48,
    members_only_unlocked:  true,
    priority_sold_out:      true,
    ai_concierge:           true,
    human_concierge:        true,
    preview_of_tier:        null,   // Top tier — no preview
    preview_count:          0,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// CANCELLATION POLICIES
// ─────────────────────────────────────────────────────────────────────────────
const CANCELLATION_POLICIES = {
  free: {
    id: 'free',
    label: 'Flexible',
    description: 'Cancel up to 1 hour before the experience for a full release.',
    cancel_hours_before: 1,
    refund_pct: 100,
    late_refund_pct: 0,
    non_refundable: false,
  },
  flexible: {
    id: 'flexible',
    label: 'Flexible',
    description: 'Cancel up to 24 hours before for a full refund.',
    cancel_hours_before: 24,
    refund_pct: 100,
    late_refund_pct: 50,   // 50% booking credit if cancelled within window
    non_refundable: false,
  },
  standard: {
    id: 'standard',
    label: 'Standard',
    description: 'Cancel up to 48 hours before for a full refund.',
    cancel_hours_before: 48,
    refund_pct: 100,
    late_refund_pct: 50,
    non_refundable: false,
  },
  moderate: {
    id: 'moderate',
    label: 'Moderate',
    description: 'Cancel up to 72 hours before for a full refund.',
    cancel_hours_before: 72,
    refund_pct: 100,
    late_refund_pct: 50,
    non_refundable: false,
  },
  firm: {
    id: 'firm',
    label: 'Firm',
    description: 'Cancel up to 5 days before for a full refund.',
    cancel_hours_before: 120,
    refund_pct: 100,
    late_refund_pct: 0,
    non_refundable: false,
  },
  strict: {
    id: 'strict',
    label: 'Strict',
    description: 'Cancel up to 7 days before for a full refund.',
    cancel_hours_before: 168,
    refund_pct: 100,
    late_refund_pct: 0,
    non_refundable: false,
  },
  non_refundable: {
    id: 'non_refundable',
    label: 'Non-Refundable',
    description: 'This is a curated experience and cannot be cancelled. All sales are final.',
    cancel_hours_before: null,
    refund_pct: 0,
    late_refund_pct: 0,
    non_refundable: true,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// VERIFICATION LEVELS (triggered by experience requirement, NOT price)
// ─────────────────────────────────────────────────────────────────────────────
const VERIFICATION_LEVELS = {
  none: {
    id: 'none',
    label: 'None',
    description: 'No verification required.',
  },
  age_21: {
    id: 'age_21',
    label: '21+ Verification',
    description: 'Must verify age 21+ via government ID before booking.',
    requires_id_scan: true,
    requires_liveness: true,
    min_age: 21,
    vendor: 'ID.me',
  },
  identity: {
    id: 'identity',
    label: 'Identity Verification',
    description: 'Full identity verification required. Government ID + biometric liveness check.',
    requires_id_scan: true,
    requires_liveness: true,
    requires_database_check: true,
    vendor: 'ID.me',
  },
  driver: {
    id: 'driver',
    label: 'Driver Verification',
    description: "Valid driver's license required. Driving record checked. No DUI in past 5 years.",
    requires_id_scan: true,
    requires_liveness: true,
    requires_database_check: true,
    requires_mvr: true,
    vendor: 'ID.me + Checkr',
  },
  medical: {
    id: 'medical',
    label: 'Medical Disclosure',
    description: 'Identity verification + medical disclosure form required.',
    requires_id_scan: true,
    requires_liveness: true,
    requires_database_check: true,
    requires_medical_disclosure: true,
    requires_emergency_contact: true,
    vendor: 'ID.me',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// POINTS SYSTEM
// ─────────────────────────────────────────────────────────────────────────────
const POINTS = {
  never_expire: true,               // Points NEVER expire
  credit_delay_hours_min: 48,       // Points credit 48-72h after experience completion
  credit_delay_hours_max: 72,
  rate: 1,                          // 1 point per $1 spent
  redemption_rate: 100,             // 100 pts = $1 value
  birthday_multiplier: 3,           // 3× during birthday week
  referral_bonus: 500,              // per successful referral
  referral_second_booking: true,    // referral credited after 2nd booking, not 1st
  referral_max_per_year: 10,
  review_bonus: 100,
  velocity_limit_30d: 50000,        // manual review if >50K pts in 30 days
};

// QE weighting
const QE_WEIGHTS = {
  free:     0.25,
  standard: 1.0,   // $1-$249
  premium:  1.5,   // $250-$499
  exclusive:2.0,   // $500+
};
const FREE_QE_CAP_PCT = 0.25;

function getQEWeight(price) {
  if (price === 0) return QE_WEIGHTS.free;
  if (price < 250) return QE_WEIGHTS.standard;
  if (price < 500) return QE_WEIGHTS.premium;
  return QE_WEIGHTS.exclusive;
}

// Installment eligibility
const INSTALLMENT_MIN_TOTAL = 500;

// ─────────────────────────────────────────────────────────────────────────────
// REDEMPTION CATALOG
// 3 core (always available) + 3 rotating (seasonal, refreshed monthly)
// NO single high-cost experience redeemable as free — discounts only on premium
// Every redemption has per-member + global quarterly caps
// ─────────────────────────────────────────────────────────────────────────────
const REDEMPTION_CATALOG = {
  core: [
    {
      id: 'credit-25',
      title: '$25 Booking Credit',
      description: 'Apply toward any experience at checkout.',
      points_cost: 2500,
      value_cents: 2500,
      type: 'credit',
      required_tier: 'rookie',
      caps: {
        per_member_per_month: 2,
        per_member_per_year: 12,
        global_per_quarter: 500,
      },
      image: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=400&h=250&fit=crop&q=85&auto=format',
      available_year_round: true,
    },
    {
      id: 'credit-50',
      title: '$50 Booking Credit',
      description: 'Apply toward any experience at checkout.',
      points_cost: 5000,
      value_cents: 5000,
      type: 'credit',
      required_tier: 'regular',
      caps: {
        per_member_per_month: 1,
        per_member_per_year: 8,
        global_per_quarter: 300,
      },
      image: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=400&h=250&fit=crop&q=85&auto=format',
      available_year_round: true,
    },
    {
      id: 'friends-first-drink',
      title: "Friend's First Drink",
      description: "Covers your friend's first drink at any dining experience you book together.",
      points_cost: 1500,
      value_cents: 1500,
      type: 'perk',
      required_tier: 'rookie',
      caps: {
        per_member_per_month: 1,
        per_member_per_year: 6,
        global_per_quarter: 400,
      },
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=250&fit=crop&q=85&auto=format',
      available_year_round: true,
    },
  ],

  // Rotating rewards — 3 active per month, changed monthly
  // Each season shows different slots
  rotating: {
    winter: [ // Dec-Feb
      {
        id: 'winter-sound-bath',
        title: 'Free Sound Bath for Two',
        description: 'Redeem for a free private sound bath session for you and one guest.',
        points_cost: 8500,
        value_cents: 24500,
        type: 'free_experience',
        required_tier: 'regular',
        experience_id: 'sound-bath-private',
        caps: {
          per_member_per_year: 1,
          global_per_quarter: 50,
        },
        image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'winter-wellness-50',
        title: '$50 Off Any Wellness Experience',
        description: 'Discount applied at checkout on any wellness booking.',
        points_cost: 4000,
        value_cents: 5000,
        type: 'discount',
        required_tier: 'regular',
        caps: {
          per_member_per_month: 1,
          per_member_per_year: 3,
          global_per_quarter: 100,
        },
        image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'winter-offline-upgrade',
        title: 'Free Bonfire Add-On',
        description: 'Add a s\'mores + drinks package to any outdoor experience at no cost.',
        points_cost: 2000,
        value_cents: 3500,
        type: 'add_on',
        required_tier: 'rookie',
        caps: {
          per_member_per_year: 2,
          global_per_quarter: 150,
        },
        image: 'https://images.unsplash.com/photo-1502740479091-635887520276?w=400&h=250&fit=crop&q=85&auto=format',
      },
    ],
    spring: [ // Mar-May
      {
        id: 'spring-pottery',
        title: 'Free Pottery Class for Two',
        description: 'Redeem for a free pottery wheel session for you and one guest.',
        points_cost: 7500,
        value_cents: 19000,
        type: 'free_experience',
        required_tier: 'regular',
        experience_id: 'pottery-wine-class',
        caps: {
          per_member_per_year: 1,
          global_per_quarter: 50,
        },
        image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'spring-outside-50',
        title: '$50 Off Any Outside Experience',
        description: 'Discount applied at checkout on any outside booking.',
        points_cost: 4000,
        value_cents: 5000,
        type: 'discount',
        required_tier: 'regular',
        caps: {
          per_member_per_month: 1,
          per_member_per_year: 3,
          global_per_quarter: 100,
        },
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'spring-market-tour',
        title: 'Free Farmers Market Tour',
        description: 'Redeem for a free guided farmers market tour.',
        points_cost: 3500,
        value_cents: 12500,
        type: 'free_experience',
        required_tier: 'regular',
        experience_id: 'farmers-market-tour-cookout',
        caps: {
          per_member_per_year: 1,
          global_per_quarter: 75,
        },
        image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=400&h=250&fit=crop&q=85&auto=format',
      },
    ],
    summer: [ // Jun-Aug
      {
        id: 'summer-picnic-addons',
        title: 'Free Beach Picnic Add-On Package',
        description: 'Add a premium charcuterie + sparkling drinks package to any outdoor experience.',
        points_cost: 2500,
        value_cents: 4500,
        type: 'add_on',
        required_tier: 'rookie',
        caps: {
          per_member_per_year: 2,
          global_per_quarter: 150,
        },
        image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'summer-offshore-75',
        title: '$75 Off Any Offshore Experience',
        description: 'Discount applied at checkout on any offshore booking.',
        points_cost: 6000,
        value_cents: 7500,
        type: 'discount',
        required_tier: 'regular',
        caps: {
          per_member_per_month: 1,
          per_member_per_year: 2,
          global_per_quarter: 75,
        },
        image: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'summer-paddleboard',
        title: 'Free Sunset Paddleboard Session',
        description: 'Redeem for a free 1-person sunset paddleboard session.',
        points_cost: 5000,
        value_cents: 14500,
        type: 'free_experience',
        required_tier: 'regular',
        experience_id: 'sunset-paddleboard-photo',
        caps: {
          per_member_per_year: 1,
          global_per_quarter: 60,
        },
        image: 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=400&h=250&fit=crop&q=85&auto=format',
      },
    ],
    fall: [ // Sep-Nov
      {
        id: 'fall-truffle-flight',
        title: 'Free Truffle Tasting Flight',
        description: 'Redeem for a free tasting flight add-on at any mushroom or truffle dining experience.',
        points_cost: 4000,
        value_cents: 6500,
        type: 'add_on',
        required_tier: 'regular',
        caps: {
          per_member_per_year: 1,
          global_per_quarter: 75,
        },
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'fall-dining-50',
        title: '$50 Off Any Dining Experience',
        description: 'Discount applied at checkout on any dining booking.',
        points_cost: 4000,
        value_cents: 5000,
        type: 'discount',
        required_tier: 'regular',
        caps: {
          per_member_per_month: 1,
          per_member_per_year: 3,
          global_per_quarter: 100,
        },
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=250&fit=crop&q=85&auto=format',
      },
      {
        id: 'fall-wine-upgrade',
        title: 'Free Wine Pairing Upgrade',
        description: 'Add a sommelier-selected wine pairing to any dining experience at no cost.',
        points_cost: 3000,
        value_cents: 5500,
        type: 'add_on',
        required_tier: 'rookie',
        caps: {
          per_member_per_year: 2,
          global_per_quarter: 120,
        },
        image: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&h=250&fit=crop&q=85&auto=format',
      },
    ],
  },

  // Local-tier only redemptions (not visible to Rookie or Regular)
  local_only: [
    {
      id: 'local-200-off-premium',
      title: '$200 Off Any Exclusive Experience',
      description: 'Take $200 off any exclusive (members-only) experience. Limited quarterly availability.',
      points_cost: 18000,
      value_cents: 20000,
      type: 'discount',
      required_tier: 'local',
      caps: {
        per_member_per_quarter: 1,
        per_member_per_year: 2,
        global_per_quarter: 25,
      },
      image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=250&fit=crop&q=85&auto=format',
    },
    {
      id: 'local-spa-50pct',
      title: '50% Off Premium Spa Day',
      description: 'Half off any full spa day experience. Maximum discount: $250.',
      points_cost: 14000,
      value_cents: 25000,
      type: 'discount',
      required_tier: 'local',
      caps: {
        per_member_per_year: 1,
        global_per_quarter: 30,
      },
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=250&fit=crop&q=85&auto=format',
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// ANTI-EXPLOIT RULES (documented for the engineering team)
// ─────────────────────────────────────────────────────────────────────────────
const ANTI_EXPLOIT = {
  redemption: {
    max_per_account_per_24h: 1,
    max_per_account_per_month: 6,
    max_per_account_per_year: 24,
    min_same_item_gap_days: 90,
    min_account_age_days: 30,
    min_paid_bookings_before_redeem: 1,
  },
  earning: {
    max_points_30d_before_review: 50000,
    points_credited_after_completion: true,
    credit_delay_hours_min: 48,
    credit_delay_hours_max: 72,
    clawback_on_refund: true,
  },
  referral: {
    credited_after_booking_number: 2,   // 2nd booking, not 1st
    min_days_after_join: 30,
    requires_unique_ip: true,
    requires_unique_device: true,
    max_per_year: 10,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// IMAGE HELPER
// ─────────────────────────────────────────────────────────────────────────────
const IMG = (id, w=800, h=500) =>
  `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&q=85&auto=format`;

// ─────────────────────────────────────────────────────────────────────────────
// EXPERIENCES (74 total — prices rebalanced, avg ~$165)
// Fields added: cancellation_policy, verification_level, waiver_required,
//               preview_for_tier (experience shows as preview for lower tier)
// ─────────────────────────────────────────────────────────────────────────────
const EXPERIENCES = [

  // ════════════════════════════════════════════════════════
  // DINING (15) — avg target: $145
  // ════════════════════════════════════════════════════════

  {
    id:'private-chef-modern-american',
    title:'Private Chef — Modern American Tasting',
    category:'dining', city:'Los Angeles',
    price_base:285, price_per_guest:75, is_free:false,
    duration_min:180,
    image:IMG('photo-1414235077428-338989a2e8c0'),
    gallery:[IMG('photo-1517248135467-4c7edcad34c4'),IMG('photo-1551782450-a2132b4ba21d')],
    description:'5-course tasting menu prepared in your home by a Michelin-trained chef. Wine pairings available.',
    host_name:'Chef Marcus Hayes', host_role:'Chef', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true,
    includes:['5-course menu','All ingredients','Setup & cleanup','Optional wine pairings'],
    rating:4.9, review_count:127,
    cancellation_policy:'moderate',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'cheese-making-workshop',
    title:'Hands-On Cheese Making Workshop',
    category:'dining', city:'New York',
    price_base:95, price_per_guest:75, is_free:false,
    duration_min:150,
    image:IMG('photo-1452195100486-9cc805987862'),
    gallery:[IMG('photo-1486297678162-eb2a19b0a32d')],
    description:'Make fresh mozzarella, ricotta, and burrata from scratch with a third-generation cheesemaker.',
    host_name:'Borgia Family Dairy', host_role:'Instructor', host_verified:true,
    max_guests:12, min_guests:2,
    tags:[], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['All ingredients','Take-home cheese','Wine & antipasto board','Recipe booklet'],
    rating:4.8, review_count:156,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'pop-up-supper-club',
    title:'Pop-Up Supper Club — Mystery Location',
    category:'dining', city:'New York',
    price_base:125, price_per_guest:125, is_free:false,
    duration_min:180,
    image:IMG('photo-1551218808-94e220e084d2'),
    gallery:[IMG('photo-1414235077428-338989a2e8c0')],
    description:'Address revealed 24 hours before. Communal tables, rotating chefs, surprise menu. A different neighborhood every weekend.',
    host_name:'Underground NYC', host_role:'Curator', host_verified:true,
    max_guests:24, min_guests:1,
    tags:[], vibes:['date-night','solo'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['5-course rotating menu','Welcome cocktail','Communal seating'],
    rating:4.7, review_count:312,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'plant-based-tasting',
    title:'Plant-Based Chef Tasting at Home',
    category:'dining', city:'Los Angeles',
    price_base:175, price_per_guest:65, is_free:false,
    duration_min:165,
    image:IMG('photo-1490645935967-10de6ba17061'),
    gallery:[IMG('photo-1473893226795-af9932fe5856')],
    description:'Innovative plant-based 5-course menu in your kitchen. Zero compromise on flavor.',
    host_name:'Chef Aria Patel', host_role:'Chef', host_verified:true,
    max_guests:10, min_guests:2,
    tags:[], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true, women_owned:true,
    includes:['5-course menu','All ingredients','Optional wine pairings','Setup & cleanup'],
    rating:4.9, review_count:88,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'omakase-private',
    title:'Private Omakase by Sushi Master',
    category:'dining', city:'New York',
    price_base:395, price_per_guest:145, is_free:false,
    duration_min:120,
    image:IMG('photo-1611143669185-af224c5e3252'),
    gallery:[IMG('photo-1579871494447-9811cf80d66c')],
    description:'14-course omakase prepared at your counter. Top-tier nigiri, fresh wasabi, premium sake.',
    host_name:'Chef Hiroshi Tanaka', host_role:'Chef', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true, bipoc_owned:true,
    includes:['14-course omakase','Premium sake pairing','Knife demo'],
    rating:5.0, review_count:47,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'truffle-hunting-tasting',
    title:'Truffle Hunting + Chef Tasting',
    category:'dining', city:'San Francisco',
    price_base:495, price_per_guest:175, is_free:false,
    duration_min:300,
    image:IMG('photo-1505761671935-60b3a7427bad'),
    gallery:[IMG('photo-1606787620819-8bdf0c44c293')],
    description:'Forage truffles with trained dogs in Sonoma, then sit down to a 4-course chef-prepared dinner featuring your finds.',
    host_name:'Sonoma Truffle Co.', host_role:'Guide', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true, women_owned:true,
    includes:['Guided forage','4-course dinner','Wine pairings','Take-home truffle salt'],
    rating:5.0, review_count:38,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'private-vineyard-pairing',
    title:'Private Vineyard Wine Pairing Dinner',
    category:'dining', city:'San Francisco',
    price_base:385, price_per_guest:125, is_free:false,
    duration_min:240,
    image:IMG('photo-1506377247377-2a5b3b417ebb'),
    gallery:[IMG('photo-1474722883778-792e7990302f')],
    description:'Reserved private dinner at a Napa boutique vineyard. Estate wines paired with a 5-course farm-to-table menu.',
    host_name:'Estate Vineyard 1845', host_role:'Curator', host_verified:true,
    max_guests:10, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true,
    includes:['5-course tasting','7 estate wines','Vineyard tour','Sommelier-led pairing'],
    rating:4.9, review_count:92,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'cocktail-history-speakeasy',
    title:'Cocktail History Speakeasy Tour',
    category:'dining', city:'Chicago',
    price_base:85, price_per_guest:85, is_free:false,
    duration_min:180,
    image:IMG('photo-1551024601-bec78aea704b'),
    gallery:[IMG('photo-1514362545857-3bc16c4c7d1b')],
    description:'Visit 4 Chicago speakeasies with a craft cocktail historian. Prohibition-era drinks, hidden entrances, untold stories.',
    host_name:'Hidden Chicago', host_role:'Guide', host_verified:true,
    max_guests:10, min_guests:1,
    tags:['21+'], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['4 venues','4 signature cocktails','Historical commentary','Walking tour'],
    rating:4.8, review_count:178,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'private-soul-food-dinner',
    title:'Private Soul Food Dinner by Chef Tasha',
    category:'dining', city:'Atlanta',
    price_base:195, price_per_guest:65, is_free:false,
    duration_min:165,
    image:IMG('photo-1606787620819-8bdf0c44c293'),
    gallery:[IMG('photo-1546069901-ba9599a7e63c')],
    description:'Modern soul food tasting menu rooted in Lowcountry tradition. Fried chicken, collards, cornbread, peach cobbler.',
    host_name:'Chef Tasha Williams', host_role:'Chef', host_verified:true,
    max_guests:12, min_guests:2,
    tags:[], vibes:['celebration','group'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true, women_owned:true,
    includes:['5-course soul food menu','All ingredients','Setup & cleanup','Family-style service'],
    rating:4.9, review_count:245,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'private-bbq-pitmaster',
    title:'Backyard BBQ with Award-Winning Pitmaster',
    category:'dining', city:'Houston',
    price_base:285, price_per_guest:55, is_free:false,
    duration_min:240,
    image:IMG('photo-1544025162-d76694265947'),
    gallery:[IMG('photo-1529193591184-b1d58069ecdd')],
    description:'Texas brisket, ribs, and sausage smoked on-site by a Memphis BBQ Network champion.',
    host_name:'Smoke Stack Pitmaster Co.', host_role:'Chef', host_verified:true,
    max_guests:30, min_guests:4,
    tags:[], vibes:['celebration','group'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true,
    includes:['Brisket, ribs, sausage','4 sides','Beverages','Setup & service'],
    rating:4.9, review_count:211,
    cancellation_policy:'moderate',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'private-tequila-mezcal-class',
    title:'Private Tequila & Mezcal Tasting',
    category:'dining', city:'Phoenix',
    price_base:115, price_per_guest:55, is_free:false,
    duration_min:120,
    image:IMG('photo-1582718411915-fb3f4ec76ac8'),
    gallery:[IMG('photo-1452195100486-9cc805987862')],
    description:'12 small-batch agave spirits from Oaxaca and Jalisco, paired with chef-prepared bites.',
    host_name:'Agave Society', host_role:'Curator', host_verified:true,
    max_guests:10, min_guests:2,
    tags:['21+'], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true,
    includes:['12 spirits','Pairing bites','Sommelier-led tasting'],
    rating:4.8, review_count:89,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'olive-oil-tasting-tour',
    title:'Olive Oil Tasting & Mill Tour',
    category:'dining', city:'Los Angeles',
    price_base:85, price_per_guest:45, is_free:false,
    duration_min:180,
    image:IMG('photo-1474942393186-87a02bc7c4c9'),
    gallery:[IMG('photo-1505740420928-5e560c06d30e')],
    description:'Tour a working California olive mill and taste 8 single-varietal oils with a sommelier-style guided pairing.',
    host_name:'Olivella Estate', host_role:'Curator', host_verified:true,
    max_guests:10, min_guests:2,
    tags:[], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Mill tour','8 olive oil tasting','Bread & accompaniments','Take-home bottle'],
    rating:4.8, review_count:64,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'mushroom-foraging-tour',
    title:'Wild Mushroom Foraging + Brunch',
    category:'dining', city:'San Francisco',
    price_base:145, price_per_guest:65, is_free:false,
    duration_min:240,
    image:IMG('photo-1542838132-92c53300491e'),
    gallery:[IMG('photo-1602976787720-e7d72d8be9a1')],
    description:'Forage chanterelles, porcini, and morels in Marin County, then return for a chef-cooked mushroom brunch.',
    host_name:'Bay Area Mycology', host_role:'Guide', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['group','solo'],
    pet_friendly:true, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Foraging guide & basket','3-course mushroom brunch','Take-home mushrooms'],
    rating:4.9, review_count:102,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'farmers-market-tour-cookout',
    title:'Farmers Market Tour + Cookout',
    category:'dining', city:'Philadelphia',
    price_base:95, price_per_guest:55, is_free:false,
    duration_min:240,
    image:IMG('photo-1488459716781-31db52582fe9'),
    gallery:[IMG('photo-1414235077428-338989a2e8c0')],
    description:'Shop the Reading Terminal Market with a chef, then cook what you bought together in a private kitchen.',
    host_name:'Chef Joey Carbone', host_role:'Chef', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Market tour','All ingredients','3-course meal','Recipe cards'],
    rating:4.7, review_count:134,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'private-tasting-menu-dc',
    title:'Private 7-Course Tasting — DC',
    category:'dining', city:'Washington DC',
    price_base:225, price_per_guest:85, is_free:false,
    duration_min:210,
    image:IMG('photo-1543353071-873f17a7a088'),
    gallery:[IMG('photo-1414235077428-338989a2e8c0')],
    description:'Seven-course tasting menu prepared by a James Beard semifinalist in an intimate private dining room.',
    host_name:'Chef Elaine Morris', host_role:'Chef', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['7-course menu','Optional wine pairings','Chef Q&A'],
    rating:4.9, review_count:56,
    cancellation_policy:'moderate',
    verification_level:'none', waiver_required:false,
  },

  // ════════════════════════════════════════════════════════
  // OFFSHORE (12) — avg target: $195
  // ════════════════════════════════════════════════════════

  {
    id:'sunset-yacht-charter',
    title:'Sunset Yacht Charter',
    category:'offshore', city:'Los Angeles',
    price_base:585, price_per_guest:85, is_free:false,
    duration_min:180,
    image:IMG('photo-1567899378494-47b22a2ae96a'),
    gallery:[IMG('photo-1542384557-0824d90731ee')],
    description:'50-foot yacht with a captain and host. Sunset cruise along the Pacific coast. BYOB welcome.',
    host_name:'Captain Eduardo Reyes', host_role:'Captain', host_verified:true,
    max_guests:12, min_guests:2,
    tags:[], vibes:['date-night','celebration','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true,
    includes:['3-hour charter','Captain & host','Coolers + ice','Bluetooth speaker'],
    rating:4.9, review_count:198,
    cancellation_policy:'firm',
    verification_level:'none', waiver_required:true,
    waiver_type:'maritime_safety',
  },
  {
    id:'jet-ski-rental-2hr',
    title:'Jet Ski Rental — 2 Hours',
    category:'offshore', city:'Los Angeles',
    price_base:185, price_per_guest:85, is_free:false,
    duration_min:120,
    image:IMG('photo-1530541930197-ff16ac917b0e'),
    gallery:[IMG('photo-1594732832278-abd644401426')],
    description:'Two-hour Sea-Doo jet ski rental with safety briefing and route options for all skill levels.',
    host_name:'Pacific Coast Watercraft', host_role:'Captain', host_verified:true,
    max_guests:4, min_guests:1,
    tags:['thrill'], vibes:['group','thrill','last-minute'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Sea-Doo jet ski','Safety briefing','Wetsuits & life jackets','Fuel'],
    rating:4.8, review_count:312,
    cancellation_policy:'standard',
    verification_level:'identity', waiver_required:true,
    waiver_type:'watercraft_activity',
  },
  {
    id:'private-boat-rental-half-day',
    title:'Private Boat Rental — Captain Included',
    category:'offshore', city:'New York',
    price_base:685, price_per_guest:50, is_free:false,
    duration_min:240,
    image:IMG('photo-1542384557-0824d90731ee'),
    gallery:[IMG('photo-1567899378494-47b22a2ae96a')],
    description:'40-foot powerboat with a USCG captain. 4 hours around Manhattan and Liberty Park.',
    host_name:'Captain James Park', host_role:'Captain', host_verified:true,
    max_guests:10, min_guests:2,
    tags:[], vibes:['date-night','celebration','group'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['4-hour charter','Captain','Bluetooth speaker','Coolers'],
    rating:4.9, review_count:156,
    cancellation_policy:'firm',
    verification_level:'none', waiver_required:true,
    waiver_type:'maritime_safety',
  },
  {
    id:'dinner-on-the-water',
    title:'Dinner on the Water — Chef + Yacht',
    category:'offshore', city:'San Francisco',
    price_base:1200, price_per_guest:265, is_free:false,
    duration_min:240,
    image:IMG('photo-1540541338287-41700207dee6'),
    gallery:[IMG('photo-1542384557-0824d90731ee')],
    description:'Private yacht charter with onboard chef preparing a 5-course dinner as you cruise the Bay.',
    host_name:'Bay Captains Collective', host_role:'Captain', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true,
    includes:['4-hour charter','Captain & onboard chef','5-course dinner','Wine pairings'],
    rating:5.0, review_count:89,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:true,
    waiver_type:'maritime_safety',
    preview_for_tier:'regular',
  },
  {
    id:'champagne-oysters-cruise',
    title:'Champagne & Oysters Cruise',
    category:'offshore', city:'New York',
    price_base:295, price_per_guest:135, is_free:false,
    duration_min:150,
    image:IMG('photo-1559339352-11d035aa65de'),
    gallery:[IMG('photo-1542384557-0824d90731ee')],
    description:'Boutique cruise with raw bar and champagne service. East River sunset, skyline views.',
    host_name:'Manhattan Sailing Club', host_role:'Host', host_verified:true,
    max_guests:14, min_guests:2,
    tags:['21+'], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['2.5-hour cruise','12 oysters per person','Champagne service','Captain'],
    rating:4.9, review_count:134,
    cancellation_policy:'standard',
    verification_level:'age_21', waiver_required:true,
    waiver_type:'maritime_safety',
  },
  {
    id:'sunset-paddleboard-photo',
    title:'Sunset Paddleboard + Photoshoot',
    category:'offshore', city:'Los Angeles',
    price_base:125, price_per_guest:55, is_free:false,
    duration_min:120,
    image:IMG('photo-1502933691298-84fc14542831'),
    gallery:[IMG('photo-1530541930197-ff16ac917b0e')],
    description:'Guided paddleboard at golden hour with a professional photographer documenting the experience.',
    host_name:'SUP Society LA', host_role:'Guide', host_verified:true,
    max_guests:8, min_guests:1,
    tags:[], vibes:['date-night','solo','group'],
    pet_friendly:true, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Paddleboard rental','Wetsuit','Photographer','20+ edited photos'],
    rating:4.8, review_count:167,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:true,
    waiver_type:'water_activity',
  },
  {
    id:'whale-watching-luxury',
    title:'Luxury Whale Watching',
    category:'offshore', city:'San Francisco',
    price_base:195, price_per_guest:115, is_free:false,
    duration_min:240,
    image:IMG('photo-1568430462989-44163eb1752f'),
    gallery:[IMG('photo-1454759215354-23ea3d65c12d')],
    description:'Small-group whale watching aboard a luxury catamaran. Marine biologist on board. Bar service included.',
    host_name:'Pacific Marine Tours', host_role:'Captain', host_verified:true,
    max_guests:14, min_guests:1,
    tags:[], vibes:['family','group','date-night'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['4-hour cruise','Marine biologist guide','Light lunch','Bar service'],
    rating:4.7, review_count:245,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:true,
    waiver_type:'maritime_safety',
  },
  {
    id:'scuba-intro-dive',
    title:'Intro to Scuba Diving',
    category:'offshore', city:'Los Angeles',
    price_base:185, price_per_guest:155, is_free:false,
    duration_min:240,
    image:IMG('photo-1551244072-5d12893278ab'),
    gallery:[IMG('photo-1530541930197-ff16ac917b0e')],
    description:'PADI-certified intro dive at Catalina. No experience needed. Pool training, then a guided ocean dive.',
    host_name:'Pacific Dive Co.', host_role:'Instructor', host_verified:true,
    max_guests:6, min_guests:1,
    tags:['thrill'], vibes:['thrill','solo','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Pool training','Boat ride to Catalina','Guided dive','All gear'],
    rating:4.9, review_count:203,
    cancellation_policy:'moderate',
    verification_level:'medical', waiver_required:true,
    waiver_type:'scuba_activity',
  },
  {
    id:'surf-lesson-photographer',
    title:'Surf Lesson + Photographer',
    category:'offshore', city:'Los Angeles',
    price_base:135, price_per_guest:85, is_free:false,
    duration_min:150,
    image:IMG('photo-1502680390469-be75c86b636f'),
    gallery:[IMG('photo-1530541930197-ff16ac917b0e')],
    description:'Private surf lesson with a former pro at El Porto. Photographer captures the whole session.',
    host_name:'El Porto Surf School', host_role:'Instructor', host_verified:true,
    max_guests:4, min_guests:1,
    tags:[], vibes:['solo','group','thrill'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Wetsuit & board','2-hour lesson','Photographer','15+ edited photos'],
    rating:4.9, review_count:178,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:true,
    waiver_type:'water_activity',
  },
  {
    id:'deep-sea-fishing-private',
    title:'Private Deep-Sea Fishing Charter',
    category:'offshore', city:'Houston',
    price_base:785, price_per_guest:165, is_free:false,
    duration_min:360,
    image:IMG('photo-1545070732-65adfffb14db'),
    gallery:[IMG('photo-1542384557-0824d90731ee')],
    description:'6-hour Gulf Coast fishing charter. All gear, bait, ice, and the captain processes your catch.',
    host_name:'Gulf Pro Fishing', host_role:'Captain', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['family','group'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['6-hour charter','All fishing gear','Bait & ice','Cleaning your catch'],
    rating:4.8, review_count:98,
    cancellation_policy:'firm',
    verification_level:'none', waiver_required:true,
    waiver_type:'maritime_safety',
  },
  {
    id:'kayak-bioluminescence',
    title:'Bioluminescent Kayak Tour',
    category:'offshore', city:'San Francisco',
    price_base:85, price_per_guest:45, is_free:false,
    duration_min:120,
    image:IMG('photo-1502720433255-614171a1835e'),
    gallery:[IMG('photo-1530541930197-ff16ac917b0e')],
    description:'Night kayak through Tomales Bay during plankton bloom season. Glowing water around your paddle.',
    host_name:'Tomales Bay Kayak', host_role:'Guide', host_verified:true,
    max_guests:12, min_guests:1,
    tags:[], vibes:['date-night','solo'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Kayak & gear','2-hour guided tour','Headlamp','Hot cocoa after'],
    rating:4.9, review_count:287,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:true,
    waiver_type:'water_activity',
  },
  {
    id:'private-island-day',
    title:'Private Island Day Trip',
    category:'offshore', city:'Los Angeles',
    price_base:1950, price_per_guest:275, is_free:false,
    duration_min:480,
    image:IMG('photo-1559827260-dc66d52bef19'),
    gallery:[IMG('photo-1564013799919-ab600027ffc6')],
    description:'8-hour exclusive charter to a private cove off Catalina. Lunch, paddleboards, snorkel gear, full crew.',
    host_name:'Pacific Yacht Club', host_role:'Captain', host_verified:true,
    max_guests:12, min_guests:4,
    tags:[], vibes:['celebration','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true,
    includes:['8-hour charter','Captain & crew','Catered lunch','Paddleboards & snorkel gear'],
    rating:5.0, review_count:41,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:true,
    waiver_type:'maritime_safety',
    preview_for_tier:'regular',
  },

  // ════════════════════════════════════════════════════════
  // ARTS & MUSIC (10) — avg target: $120
  // ════════════════════════════════════════════════════════

  {
    id:'private-gallery-curator-tour',
    title:'Private Gallery Curator Tour',
    category:'arts', city:'New York',
    price_base:195, price_per_guest:85, is_free:false,
    duration_min:120,
    image:IMG('photo-1545987796-200677ee1011'),
    gallery:[IMG('photo-1460661419201-fd4cecdf8a8b')],
    description:'After-hours private tour of a Chelsea gallery with the curator. Champagne, conversation, behind-the-scenes access.',
    host_name:'Chelsea Arts Collective', host_role:'Curator', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true, women_owned:true,
    includes:['Private after-hours tour','Champagne','Curator-led conversation'],
    rating:5.0, review_count:67,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'jazz-club-reserved-table',
    title:'Reserved Table at Iconic Jazz Club',
    category:'arts', city:'New York',
    price_base:125, price_per_guest:75, is_free:false,
    duration_min:180,
    image:IMG('photo-1514525253161-7a46d19cd819'),
    gallery:[IMG('photo-1493225457124-a3eb161ffa5f')],
    description:'Reserved best-in-the-house table at Smalls or Village Vanguard. Two sets, dinner service, no waiting.',
    host_name:'Village Jazz Concierge', host_role:'Host', host_verified:true,
    max_guests:4, min_guests:1,
    tags:['21+'], vibes:['date-night','solo'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['2 jazz sets','Reserved table','Dinner service','Drink minimum included'],
    rating:4.9, review_count:421,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'pottery-wine-class',
    title:'Pottery Wheel Class with Wine',
    category:'arts', city:'Los Angeles',
    price_base:85, price_per_guest:85, is_free:false,
    duration_min:150,
    image:IMG('photo-1565193566173-7a0ee3dbe261'),
    gallery:[IMG('photo-1493225457124-a3eb161ffa5f')],
    description:'Throw a bowl, mug, or vase from clay. Wine and snacks included. We fire and ship your piece.',
    host_name:'Clay Studio LA', host_role:'Instructor', host_verified:true,
    max_guests:12, min_guests:1,
    tags:['21+'], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['All clay & tools','Wine & snacks','2 fired pieces shipped'],
    rating:4.8, review_count:256,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'glassblowing-workshop',
    title:'Hands-On Glassblowing Workshop',
    category:'arts', city:'Philadelphia',
    price_base:145, price_per_guest:125, is_free:false,
    duration_min:120,
    image:IMG('photo-1516981442399-a91139e20ff8'),
    gallery:[IMG('photo-1565193566173-7a0ee3dbe261')],
    description:'Make your own glass paperweight or ornament with a master glassblower in a working hot shop.',
    host_name:'Liberty Glass Studio', host_role:'Instructor', host_verified:true,
    max_guests:4, min_guests:1,
    tags:[], vibes:['date-night','solo'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Safety gear','Master-led session','Take-home piece (shipped)'],
    rating:4.9, review_count:189,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:true,
    waiver_type:'hot_shop_safety',
  },
  {
    id:'urban-sketch-tour',
    title:'Urban Sketch Tour with Local Artist',
    category:'arts', city:'Chicago',
    price_base:55, price_per_guest:35, is_free:false,
    duration_min:180,
    image:IMG('photo-1513364776144-60967b0f800f'),
    gallery:[IMG('photo-1577720580479-7d839d829c73')],
    description:'Walk Chicago neighborhoods sketching architecture, street life, and skyline with a working illustrator.',
    host_name:'Sketch Chicago', host_role:'Instructor', host_verified:true,
    max_guests:8, min_guests:1,
    tags:[], vibes:['solo','group'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Sketchbook & pencils','Walking tour','Coffee break'],
    rating:4.7, review_count:88,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'architecture-tour-private',
    title:'Private Architecture Tour',
    category:'arts', city:'Chicago',
    price_base:115, price_per_guest:55, is_free:false,
    duration_min:180,
    image:IMG('photo-1486325212027-8081e485255e'),
    gallery:[IMG('photo-1485628390555-1a7bd3c2f3b4')],
    description:'Three-hour walking tour of Chicago landmarks led by a licensed architect.',
    host_name:'Chicago Architecture Lab', host_role:'Guide', host_verified:true,
    max_guests:8, min_guests:1,
    tags:['accessible'], vibes:['date-night','family','solo'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Custom route','Licensed architect guide','Architecture booklet'],
    rating:4.9, review_count:167,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'behind-scenes-museum',
    title:'After-Hours Museum Tour',
    category:'arts', city:'New York',
    price_base:385, price_per_guest:165, is_free:false,
    duration_min:120,
    image:IMG('photo-1554907984-15263bfd63bd'),
    gallery:[IMG('photo-1545987796-200677ee1011')],
    description:'After-hours private tour at the MoMA, Whitney, or Met. Curator-guided. Champagne in the gallery.',
    host_name:'NYC Museum Concierge', host_role:'Curator', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:false,
    includes:['After-hours access','Curator guide','Champagne service'],
    rating:5.0, review_count:52,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'live-painting-couples',
    title:'Live Painting Class for Couples',
    category:'arts', city:'Atlanta',
    price_base:65, price_per_guest:65, is_free:false,
    duration_min:120,
    image:IMG('photo-1513364776144-60967b0f800f'),
    gallery:[IMG('photo-1493225457124-a3eb161ffa5f')],
    description:'Side-by-side painting class for couples. Wine, music, and one collaborative final piece to take home.',
    host_name:'Brush & Bottle ATL', host_role:'Instructor', host_verified:true,
    max_guests:8, min_guests:2,
    tags:['21+'], vibes:['date-night'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true, women_owned:true,
    includes:['All supplies','Wine & snacks','Collaborative canvas','Take-home pieces'],
    rating:4.8, review_count:312,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'private-violinist-dinner',
    title:'Private Violinist for Dinner',
    category:'arts', city:'Washington DC',
    price_base:385, price_per_guest:0, is_free:false,
    duration_min:90,
    image:IMG('photo-1487180144351-b8472da7d491'),
    gallery:[IMG('photo-1493225457124-a3eb161ffa5f')],
    description:'Concert violinist plays at your home or restaurant during dinner. Custom playlist.',
    host_name:'Capitol Strings', host_role:'Curator', host_verified:true,
    max_guests:50, min_guests:1,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['90-min performance','Custom playlist','Travel within DC'],
    rating:5.0, review_count:76,
    cancellation_policy:'moderate',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'free-friday-art-walk',
    title:'Free Friday Art Walk',
    category:'arts', city:'Los Angeles',
    price_base:0, price_per_guest:0, is_free:true,
    duration_min:180,
    image:IMG('photo-1577720580479-7d839d829c73'),
    gallery:[IMG('photo-1460661419201-fd4cecdf8a8b')],
    description:'Self-guided walking tour of DTLA Arts District galleries. Curated route, openings list, free wine pours.',
    host_name:'DTLA Arts District', host_role:'Curator', host_verified:true,
    max_guests:999, min_guests:1,
    tags:['accessible'], vibes:['solo','group','last-minute'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Curated walking route','Gallery openings list','Free wine pours'],
    rating:4.6, review_count:893,
    cancellation_policy:'free',
    verification_level:'none', waiver_required:false,
  },

  // ════════════════════════════════════════════════════════
  // ADVENTURE (12) — avg target: $185
  // ════════════════════════════════════════════════════════

  {
    id:'supercar-driving-course',
    title:'Supercar Driving Course',
    category:'adventure', city:'Los Angeles',
    price_base:585, price_per_guest:585, is_free:false,
    duration_min:240,
    image:IMG('photo-1503376780353-7e6692767b70'),
    gallery:[IMG('photo-1492144534655-ae79c964c9d7')],
    description:'Drive a Lamborghini, Ferrari, and Porsche on a closed track with a pro driver as your instructor.',
    host_name:'West Coast Track Club', host_role:'Instructor', host_verified:true,
    max_guests:4, min_guests:1,
    tags:['thrill'], vibes:['thrill','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true,
    includes:['3 different supercars','20 total laps','Pro driver instructor','Helmet & gear'],
    rating:5.0, review_count:134,
    cancellation_policy:'non_refundable',
    verification_level:'driver', waiver_required:true,
    waiver_type:'motorsport_activity',
    preview_for_tier:'regular',
  },
  {
    id:'hot-air-balloon-sunrise',
    title:'Sunrise Hot Air Balloon',
    category:'adventure', city:'Phoenix',
    price_base:385, price_per_guest:245, is_free:false,
    duration_min:240,
    image:IMG('photo-1507608443039-bfde4fbcd142'),
    gallery:[IMG('photo-1495820689848-1eef3727b25c')],
    description:'Hour-long balloon flight over the Sonoran Desert at sunrise. Champagne brunch on landing.',
    host_name:'Desert Balloon Co.', host_role:'Captain', host_verified:true,
    max_guests:8, min_guests:2,
    tags:['thrill'], vibes:['date-night','celebration','thrill'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['1-hour flight','Champagne brunch','Photos','Flight certificate'],
    rating:4.9, review_count:256,
    cancellation_policy:'strict',
    verification_level:'medical', waiver_required:true,
    waiver_type:'aerial_activity',
  },
  {
    id:'helicopter-city-tour',
    title:'Helicopter City Tour',
    category:'adventure', city:'New York',
    price_base:485, price_per_guest:235, is_free:false,
    duration_min:60,
    image:IMG('photo-1559117776-9bdcb2c80f60'),
    gallery:[IMG('photo-1473893604213-3df9c15611c0')],
    description:'Private helicopter tour over Manhattan, Statue of Liberty, and Central Park. Doors-off option available.',
    host_name:'Manhattan Sky Tours', host_role:'Captain', host_verified:true,
    max_guests:4, min_guests:1,
    tags:['thrill'], vibes:['celebration','thrill','date-night'],
    pet_friendly:false, kid_friendly:true,
    exclusive:true, points_mult:2, small_business:true,
    includes:['30-min flight','Pilot narration','Photos','Doors-off option'],
    rating:4.9, review_count:312,
    cancellation_policy:'non_refundable',
    verification_level:'identity', waiver_required:true,
    waiver_type:'aerial_activity',
    preview_for_tier:'regular',
  },
  {
    id:'indoor-skydiving',
    title:'Indoor Skydiving Session',
    category:'adventure', city:'Atlanta',
    price_base:85, price_per_guest:65, is_free:false,
    duration_min:90,
    image:IMG('photo-1521673252667-e05da380b252'),
    gallery:[IMG('photo-1551632436-cbf8dd35adfa')],
    description:'Two flights in a vertical wind tunnel with an instructor. Feel the rush of freefall without the plane.',
    host_name:'iFly Atlanta', host_role:'Instructor', host_verified:true,
    max_guests:6, min_guests:1,
    tags:['thrill'], vibes:['family','thrill','group'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:false,
    includes:['2 wind tunnel flights','Gear','Instructor','Video recording'],
    rating:4.7, review_count:567,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:true,
    waiver_type:'skydiving_activity',
  },
  {
    id:'paragliding-tandem',
    title:'Tandem Paragliding Flight',
    category:'adventure', city:'Los Angeles',
    price_base:225, price_per_guest:225, is_free:false,
    duration_min:90,
    image:IMG('photo-1551632436-cbf8dd35adfa'),
    gallery:[IMG('photo-1515125520141-3e3b67bc4f60')],
    description:'Soar over Malibu cliffs with a certified pilot strapped in tandem. 30 minutes airborne.',
    host_name:'Malibu Paragliding', host_role:'Instructor', host_verified:true,
    max_guests:2, min_guests:1,
    tags:['thrill'], vibes:['thrill','date-night'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Tandem flight','GoPro footage','Photos','All gear'],
    rating:4.9, review_count:189,
    cancellation_policy:'moderate',
    verification_level:'medical', waiver_required:true,
    waiver_type:'aerial_activity',
  },
  {
    id:'axe-throwing-pizza',
    title:'Axe Throwing + Wood-Fired Pizza',
    category:'adventure', city:'Philadelphia',
    price_base:75, price_per_guest:55, is_free:false,
    duration_min:150,
    image:IMG('photo-1565299624946-b28f40a0ae38'),
    gallery:[IMG('photo-1551632436-cbf8dd35adfa')],
    description:'90 minutes of guided axe throwing competition, followed by wood-fired pizza and craft beer.',
    host_name:'Liberty Throws', host_role:'Instructor', host_verified:true,
    max_guests:16, min_guests:2,
    tags:['21+'], vibes:['group','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['90-min axe session','Coach','Wood-fired pizza','2 craft beers each'],
    rating:4.8, review_count:423,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:true,
    waiver_type:'axe_throwing',
  },
  {
    id:'bouldering-brewery',
    title:'Bouldering Class + Brewery',
    category:'adventure', city:'Phoenix',
    price_base:75, price_per_guest:55, is_free:false,
    duration_min:180,
    image:IMG('photo-1522163182402-834f871fd851'),
    gallery:[IMG('photo-1565299624946-b28f40a0ae38')],
    description:'Two-hour bouldering intro at an indoor gym, then walk to a craft brewery for tastings.',
    host_name:'Climb Phoenix', host_role:'Instructor', host_verified:true,
    max_guests:8, min_guests:1,
    tags:['21+'], vibes:['group','solo'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['2-hour climb session','Shoes & chalk','Brewery flight'],
    rating:4.7, review_count:156,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:true,
    waiver_type:'climbing_activity',
  },
  {
    id:'desert-glamping',
    title:'Desert Glamping Overnight',
    category:'adventure', city:'Phoenix',
    price_base:465, price_per_guest:135, is_free:false,
    duration_min:1080,
    image:IMG('photo-1539571696357-5a69c17a67c6'),
    gallery:[IMG('photo-1504280390367-361c6d9f38f4')],
    description:'Luxury yurt under the stars. Sonoran sunset, fire pit, dinner included, breakfast in the morning.',
    host_name:'Sonoran Stars Glamping', host_role:'Host', host_verified:true,
    max_guests:4, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:true, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Yurt overnight','Dinner & breakfast','Stargazing telescope','Hot tub access'],
    rating:4.9, review_count:211,
    cancellation_policy:'firm',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'sunset-hike-private-dinner',
    title:'Sunset Hike + Private Chef Dinner',
    category:'adventure', city:'Los Angeles',
    price_base:325, price_per_guest:125, is_free:false,
    duration_min:240,
    image:IMG('photo-1551632811-561732d1e306'),
    gallery:[IMG('photo-1414235077428-338989a2e8c0')],
    description:'Guided golden-hour hike in the Hollywood Hills, then a private outdoor chef-prepared 3-course meal.',
    host_name:'Trail & Table', host_role:'Guide', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['date-night','celebration'],
    pet_friendly:true, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true,
    includes:['Sunset hike','Private table','3-course chef dinner','Wine pairings'],
    rating:4.9, review_count:89,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'escape-room-chef-dinner',
    title:'Escape Room + Chef-Prepared Dinner',
    category:'adventure', city:'Dallas',
    price_base:195, price_per_guest:85, is_free:false,
    duration_min:180,
    image:IMG('photo-1606160112824-c6df21068e02'),
    gallery:[IMG('photo-1546069901-ba9599a7e63c')],
    description:'60-minute themed escape room followed by a 3-course chef dinner in a private room.',
    host_name:'Mystery Dallas', host_role:'Host', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['date-night','group','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Escape room','3-course themed dinner','Private room'],
    rating:4.8, review_count:167,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'vintage-car-rally',
    title:'Vintage Car Rally — Half Day',
    category:'adventure', city:'San Francisco',
    price_base:385, price_per_guest:225, is_free:false,
    duration_min:240,
    image:IMG('photo-1492144534655-ae79c964c9d7'),
    gallery:[IMG('photo-1469285994282-454ceb49e63c')],
    description:'Drive a vintage 1965 Mustang or Porsche 356 along the Pacific Coast Highway. Picnic lunch in Big Sur.',
    host_name:'Coastal Classics SF', host_role:'Host', host_verified:true,
    max_guests:4, min_guests:1,
    tags:[], vibes:['date-night','thrill'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true,
    includes:['Vintage car rental','Driver option available','Picnic lunch','Photographer'],
    rating:4.9, review_count:67,
    cancellation_policy:'non_refundable',
    verification_level:'driver', waiver_required:true,
    waiver_type:'motorsport_activity',
    preview_for_tier:'regular',
  },
  {
    id:'free-trail-running',
    title:'Free Trail Running Group',
    category:'adventure', city:'Los Angeles',
    price_base:0, price_per_guest:0, is_free:true,
    duration_min:75,
    image:IMG('photo-1571008887538-b36bb32f4571'),
    gallery:[IMG('photo-1551632811-561732d1e306')],
    description:'Free guided trail run in Griffith Park every Saturday morning. All paces welcome. Coffee after.',
    host_name:'LA Trail Runners', host_role:'Guide', host_verified:true,
    max_guests:50, min_guests:1,
    tags:[], vibes:['solo','group','last-minute'],
    pet_friendly:true, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Guided run','All paces welcome','Coffee meetup after'],
    rating:4.8, review_count:1247,
    cancellation_policy:'free',
    verification_level:'none', waiver_required:false,
  },

  // ════════════════════════════════════════════════════════
  // WELLNESS (10) — avg target: $95
  // ════════════════════════════════════════════════════════

  {
    id:'sound-bath-private',
    title:'Private Sound Bath at Home',
    category:'wellness', city:'Los Angeles',
    price_base:195, price_per_guest:35, is_free:false,
    duration_min:90,
    image:IMG('photo-1545389336-cf090694435e'),
    gallery:[IMG('photo-1591291621164-2c6367723315')],
    description:'Guided sound bath in your home with crystal bowls, gongs, and chimes.',
    host_name:'Aurora Sound Healing', host_role:'Instructor', host_verified:true,
    max_guests:12, min_guests:1,
    tags:['accessible'], vibes:['solo','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true, women_owned:true,
    includes:['90-min sound bath','Crystal bowls & gongs','Mats provided'],
    rating:4.9, review_count:234,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'float-tank-session',
    title:'Float Tank Session',
    category:'wellness', city:'New York',
    price_base:85, price_per_guest:0, is_free:false,
    duration_min:90,
    image:IMG('photo-1620916566398-39f1143ab7be'),
    gallery:[IMG('photo-1545389336-cf090694435e')],
    description:'60-minute private float tank session. Zero gravity, zero stimulation, complete reset.',
    host_name:'Float NYC', host_role:'Host', host_verified:true,
    max_guests:1, min_guests:1,
    tags:['accessible'], vibes:['solo'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['60-min float','Towels & toiletries','Post-float lounge'],
    rating:4.8, review_count:312,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'forest-bathing',
    title:'Forest Bathing Guided Walk',
    category:'wellness', city:'San Francisco',
    price_base:65, price_per_guest:45, is_free:false,
    duration_min:150,
    image:IMG('photo-1448375240586-882707db888b'),
    gallery:[IMG('photo-1542273917363-3b1817f69a2d')],
    description:'Slow guided walk through Muir Woods with a certified forest bathing guide. Tea ceremony at the end.',
    host_name:'Marin Mindful Walks', host_role:'Guide', host_verified:true,
    max_guests:8, min_guests:1,
    tags:['accessible'], vibes:['solo','group'],
    pet_friendly:true, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['2.5-hour guided walk','Tea ceremony','Mindfulness practices'],
    rating:4.9, review_count:178,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'rooftop-yoga-sunset',
    title:'Rooftop Sunset Yoga',
    category:'wellness', city:'Chicago',
    price_base:35, price_per_guest:25, is_free:false,
    duration_min:75,
    image:IMG('photo-1575052814086-f385e2e2ad1b'),
    gallery:[IMG('photo-1591291621164-2c6367723315')],
    description:'All-levels yoga class on a downtown Chicago rooftop. Skyline views, sunset, mat provided.',
    host_name:'Loop Yoga Collective', host_role:'Instructor', host_verified:true,
    max_guests:25, min_guests:1,
    tags:[], vibes:['solo','group','last-minute'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['75-min class','Mat included','Welcome kombucha'],
    rating:4.8, review_count:567,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'private-massage-couples',
    title:"Couples' In-Home Massage",
    category:'wellness', city:'Los Angeles',
    price_base:295, price_per_guest:0, is_free:false,
    duration_min:90,
    image:IMG('photo-1544161515-4ab6ce6db874'),
    gallery:[IMG('photo-1540555700478-4be289fbecef')],
    description:'Two licensed therapists arrive at your home. Synchronized 90-minute massage for two.',
    host_name:'Stillpoint Mobile Massage', host_role:'Instructor', host_verified:true,
    max_guests:2, min_guests:2,
    tags:[], vibes:['date-night'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['2 therapists','90-min synchronized massage','All equipment','Premium oils'],
    rating:4.9, review_count:234,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'breathwork-class',
    title:'Group Breathwork Class',
    category:'wellness', city:'Atlanta',
    price_base:25, price_per_guest:25, is_free:false,
    duration_min:75,
    image:IMG('photo-1591291621164-2c6367723315'),
    gallery:[IMG('photo-1575052814086-f385e2e2ad1b')],
    description:'Group breathwork class with live music. 75 minutes of guided pranayama for clarity and energy.',
    host_name:'Breath ATL', host_role:'Instructor', host_verified:true,
    max_guests:30, min_guests:1,
    tags:['accessible'], vibes:['solo','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true,
    includes:['75-min class','Live music','Mat & blanket','Tea after'],
    rating:4.8, review_count:189,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'spa-day-private',
    title:'Full Spa Day at Boutique Spa',
    category:'wellness', city:'San Francisco',
    price_base:465, price_per_guest:385, is_free:false,
    duration_min:360,
    image:IMG('photo-1540555700478-4be289fbecef'),
    gallery:[IMG('photo-1544161515-4ab6ce6db874')],
    description:'6-hour spa day: massage, facial, body scrub, sauna, hot tub, and 3-course lunch. Private cabana.',
    host_name:'Sage Sanctuary Spa', host_role:'Host', host_verified:true,
    max_guests:4, min_guests:1,
    tags:[], vibes:['solo','date-night','celebration'],
    pet_friendly:false, kid_friendly:false,
    exclusive:true, points_mult:2, small_business:true, women_owned:true,
    includes:['90-min massage','Facial','Body scrub','Sauna & hot tub','Lunch'],
    rating:5.0, review_count:145,
    cancellation_policy:'non_refundable',
    verification_level:'none', waiver_required:false,
    preview_for_tier:'regular',
  },
  {
    id:'cryotherapy-iv',
    title:'Cryotherapy + IV Drip Combo',
    category:'wellness', city:'Los Angeles',
    price_base:245, price_per_guest:0, is_free:false,
    duration_min:90,
    image:IMG('photo-1620916566398-39f1143ab7be'),
    gallery:[IMG('photo-1544161515-4ab6ce6db874')],
    description:'3-minute whole-body cryotherapy followed by a 45-min vitamin IV drip. Recovery + immunity boost.',
    host_name:'Restore LA', host_role:'Instructor', host_verified:true,
    max_guests:1, min_guests:1,
    tags:[], vibes:['solo'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:false,
    includes:['3-min cryo','45-min IV drip','Vitamin C, B-complex, glutathione'],
    rating:4.7, review_count:98,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:true,
    waiver_type:'medical_wellness',
  },
  {
    id:'guided-meditation-park',
    title:'Free Guided Meditation in the Park',
    category:'wellness', city:'New York',
    price_base:0, price_per_guest:0, is_free:true,
    duration_min:60,
    image:IMG('photo-1545389336-cf090694435e'),
    gallery:[IMG('photo-1591291621164-2c6367723315')],
    description:'Free 60-minute guided meditation in Central Park every Sunday morning. All experience levels.',
    host_name:'NYC Mindful Sundays', host_role:'Instructor', host_verified:true,
    max_guests:100, min_guests:1,
    tags:['accessible'], vibes:['solo','group','last-minute'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['60-min guided meditation','Optional mat'],
    rating:4.7, review_count:1834,
    cancellation_policy:'free',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'hike-meditation-retreat',
    title:'Half-Day Hike + Meditation Retreat',
    category:'wellness', city:'Phoenix',
    price_base:135, price_per_guest:85, is_free:false,
    duration_min:300,
    image:IMG('photo-1551632811-561732d1e306'),
    gallery:[IMG('photo-1542273917363-3b1817f69a2d')],
    description:'Guided desert hike, mid-trail meditation, journaling station, healthy lunch served at base camp.',
    host_name:'Sonoran Stillness', host_role:'Guide', host_verified:true,
    max_guests:10, min_guests:1,
    tags:['accessible'], vibes:['solo','group'],
    pet_friendly:true, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Guided hike','Meditation session','Journaling station','Lunch'],
    rating:4.8, review_count:134,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },

  // ════════════════════════════════════════════════════════
  // OUTSIDE (8) — avg target: $95
  // ════════════════════════════════════════════════════════

  {
    id:'rooftop-cocktail-class',
    title:'Rooftop Cocktail Class',
    category:'outside', city:'New York',
    price_base:75, price_per_guest:65, is_free:false,
    duration_min:120,
    image:IMG('photo-1514362545857-3bc16c4c7d1b'),
    gallery:[IMG('photo-1551024601-bec78aea704b')],
    description:'Make 4 craft cocktails on a downtown NYC rooftop. Bartender-led, sunset view.',
    host_name:'Skyline Cocktails', host_role:'Instructor', host_verified:true,
    max_guests:16, min_guests:1,
    tags:['21+'], vibes:['date-night','group'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['4 craft cocktails','All ingredients','Bartender-led','Recipe cards'],
    rating:4.8, review_count:423,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'beach-bonfire-private',
    title:'Private Beach Bonfire',
    category:'outside', city:'Los Angeles',
    price_base:185, price_per_guest:25, is_free:false,
    duration_min:180,
    image:IMG('photo-1502740479091-635887520276'),
    gallery:[IMG('photo-1504281673184-bbb22a4ab4cb')],
    description:"Reserved fire pit, beach lounge setup, s'mores kit, Bluetooth speaker. Permit handled.",
    host_name:'Coastal Bonfires', host_role:'Host', host_verified:true,
    max_guests:20, min_guests:4,
    tags:[], vibes:['date-night','celebration','group','family'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Fire pit & permit','Lounge setup',"s'mores kit",'Bluetooth speaker'],
    rating:4.9, review_count:289,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'beach-picnic-private',
    title:'Private Beach Picnic',
    category:'outside', city:'Los Angeles',
    price_base:195, price_per_guest:35, is_free:false,
    duration_min:180,
    image:IMG('photo-1517457373958-b7bdd4587205'),
    gallery:[IMG('photo-1502740479091-635887520276')],
    description:'Curated beach picnic setup with rugs, low table, charcuterie board, fresh fruit, sparkling drinks.',
    host_name:'Sandy Soirees LA', host_role:'Host', host_verified:true,
    max_guests:12, min_guests:2,
    tags:[], vibes:['date-night','celebration','family'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Picnic setup & teardown','Charcuterie board','Sparkling drinks','Photographer (add-on)'],
    rating:4.9, review_count:167,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'outdoor-movie-night',
    title:'Outdoor Movie Night Setup',
    category:'outside', city:'Los Angeles',
    price_base:225, price_per_guest:0, is_free:false,
    duration_min:240,
    image:IMG('photo-1485846234645-a62644f84728'),
    gallery:[IMG('photo-1574267432553-4b4628081c31')],
    description:'Inflatable 12-foot outdoor screen, projector, sound system, bean bags. Choose any film.',
    host_name:'Backyard Cinema Co.', host_role:'Host', host_verified:true,
    max_guests:30, min_guests:2,
    tags:[], vibes:['date-night','group','family'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['12-ft screen','Projector & sound','Bean bags','Setup & breakdown'],
    rating:4.8, review_count:156,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'rooftop-stargazing',
    title:'Rooftop Stargazing with Astronomer',
    category:'outside', city:'San Francisco',
    price_base:115, price_per_guest:45, is_free:false,
    duration_min:120,
    image:IMG('photo-1532074205216-d0e1f4b87368'),
    gallery:[IMG('photo-1495820689848-1eef3727b25c')],
    description:"Rooftop session with telescopes and a working astronomer. View Saturn's rings, Jupiter, the Moon up close.",
    host_name:'Bay Astronomy Club', host_role:'Guide', host_verified:true,
    max_guests:12, min_guests:1,
    tags:[], vibes:['date-night','family','solo'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Telescope access','Astronomer guide','Hot drinks'],
    rating:4.9, review_count:178,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'silent-disco-park',
    title:'Silent Disco in the Park',
    category:'outside', city:'Chicago',
    price_base:25, price_per_guest:25, is_free:false,
    duration_min:180,
    image:IMG('photo-1574267432553-4b4628081c31'),
    gallery:[IMG('photo-1493225457124-a3eb161ffa5f')],
    description:'Silent disco headphone party in Millennium Park. 3 DJs on different channels.',
    host_name:'Silent Chicago', host_role:'Host', host_verified:true,
    max_guests:200, min_guests:1,
    tags:[], vibes:['group','last-minute'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Headphones','3 DJ channels','Park permit'],
    rating:4.7, review_count:567,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'outdoor-comedy-show',
    title:'Outdoor Comedy Show',
    category:'outside', city:'Los Angeles',
    price_base:35, price_per_guest:25, is_free:false,
    duration_min:120,
    image:IMG('photo-1542038784456-1ea8e935640e'),
    gallery:[IMG('photo-1574267432553-4b4628081c31')],
    description:'Saturday night outdoor comedy show with rotating LA stand-ups. BYOB, food truck on site.',
    host_name:'Echo Park Comedy', host_role:'Host', host_verified:true,
    max_guests:100, min_guests:1,
    tags:['21+'], vibes:['group','date-night','last-minute'],
    pet_friendly:false, kid_friendly:false,
    exclusive:false, points_mult:1, small_business:true,
    includes:['90-min show','Reserved blanket spot','Food truck access'],
    rating:4.6, review_count:312,
    cancellation_policy:'flexible',
    verification_level:'age_21', waiver_required:false,
  },
  {
    id:'free-park-yoga',
    title:'Free Sunset Park Yoga',
    category:'outside', city:'Phoenix',
    price_base:0, price_per_guest:0, is_free:true,
    duration_min:60,
    image:IMG('photo-1575052814086-f385e2e2ad1b'),
    gallery:[IMG('photo-1591291621164-2c6367723315')],
    description:'Free outdoor yoga at Papago Park every Wednesday at sunset. Bring a mat. All levels welcome.',
    host_name:'Phoenix Park Yoga', host_role:'Instructor', host_verified:true,
    max_guests:60, min_guests:1,
    tags:['accessible'], vibes:['solo','group','last-minute'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['60-min class','BYO mat'],
    rating:4.8, review_count:1167,
    cancellation_policy:'free',
    verification_level:'none', waiver_required:false,
  },

  // ════════════════════════════════════════════════════════
  // KIDS (7) — experiences DESIGNED for children
  // ════════════════════════════════════════════════════════

  {
    id:'kids-cooking-class',
    title:'Kids Cooking Class',
    category:'kids', city:'New York',
    price_base:75, price_per_guest:55, is_free:false,
    duration_min:120,
    image:IMG('photo-1607478900766-efe13248b125'),
    gallery:[IMG('photo-1414235077428-338989a2e8c0')],
    description:'Hands-on cooking class for kids 6-12. Make pizza from scratch, cookies, and a kid-friendly main dish.',
    host_name:'Lil Chef Studios', host_role:'Instructor', host_verified:true,
    max_guests:8, min_guests:1,
    tags:[], vibes:['family'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['All ingredients','Aprons','Take-home recipes','Kids eat their creations'],
    rating:4.9, review_count:423,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'aquarium-behind-scenes',
    title:'Aquarium Behind-the-Scenes',
    category:'kids', city:'Atlanta',
    price_base:185, price_per_guest:75, is_free:false,
    duration_min:150,
    image:IMG('photo-1544551763-46a013bb70d5'),
    gallery:[IMG('photo-1530560008797-edc81f7b9aae')],
    description:'Behind-the-scenes aquarium tour for kids. Touch tank, feed sharks, meet the marine biologists.',
    host_name:'Georgia Aquarium', host_role:'Guide', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['family'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:false,
    includes:['Behind-the-scenes tour','Touch tank','Shark feeding','Photo with biologist'],
    rating:5.0, review_count:312,
    cancellation_policy:'moderate',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'museum-sleepover',
    title:'Museum Sleepover for Kids',
    category:'kids', city:'Chicago',
    price_base:145, price_per_guest:125, is_free:false,
    duration_min:720,
    image:IMG('photo-1551033406-611cf9a28f67'),
    gallery:[IMG('photo-1555854877-bab0e564b8d5')],
    description:'Overnight sleepover at the Museum of Science and Industry. Sleeping bags in the main hall.',
    host_name:'Chicago Museums Family', host_role:'Host', host_verified:true,
    max_guests:6, min_guests:2,
    tags:[], vibes:['family','celebration'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:false,
    includes:['Overnight stay','Sleeping bag rental','Pizza dinner','Continental breakfast','Late-night exhibits'],
    rating:4.9, review_count:234,
    cancellation_policy:'firm',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'treasure-hunt-park',
    title:'Themed Treasure Hunt for Kids',
    category:'kids', city:'San Francisco',
    price_base:115, price_per_guest:25, is_free:false,
    duration_min:120,
    image:IMG('photo-1502086223501-7ea6ecd79368'),
    gallery:[IMG('photo-1517245386807-bb43f82c33c4')],
    description:'Pirate, princess, or detective-themed treasure hunt in Golden Gate Park. Costumes, clues, and a final treasure chest.',
    host_name:'Golden Hunts SF', host_role:'Host', host_verified:true,
    max_guests:12, min_guests:4,
    tags:[], vibes:['family','celebration'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, women_owned:true,
    includes:['Costumes','Clue maps','Treasure chest with prizes','Snack box'],
    rating:4.9, review_count:189,
    cancellation_policy:'standard',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'science-experiment-class',
    title:'Mad Scientist Class',
    category:'kids', city:'Houston',
    price_base:95, price_per_guest:55, is_free:false,
    duration_min:90,
    image:IMG('photo-1532094349884-543bc11b234d'),
    gallery:[IMG('photo-1518349619113-03114f06ac3a')],
    description:'Hands-on science experiments for kids: slime, volcanoes, dry ice. Lab coats provided.',
    host_name:'Houston STEM Lab', host_role:'Instructor', host_verified:true,
    max_guests:10, min_guests:1,
    tags:[], vibes:['family'],
    pet_friendly:false, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true, bipoc_owned:true,
    includes:['6 experiments','Lab coats','Take-home science kit'],
    rating:4.8, review_count:312,
    cancellation_policy:'flexible',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'family-camping-adventure',
    title:'Family Camping Adventure',
    category:'kids', city:'Phoenix',
    price_base:365, price_per_guest:125, is_free:false,
    duration_min:1080,
    image:IMG('photo-1504280390367-361c6d9f38f4'),
    gallery:[IMG('photo-1539571696357-5a69c17a67c6')],
    description:'Pre-set up tent, gear, fire pit, kid-led activities. Stargazing, campfire stories, hot chocolate.',
    host_name:'Family Adventure Co.', host_role:'Host', host_verified:true,
    max_guests:8, min_guests:2,
    tags:[], vibes:['family'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Tent & sleeping bags','Fire pit','Dinner & breakfast','Stargazing telescope'],
    rating:4.9, review_count:167,
    cancellation_policy:'firm',
    verification_level:'none', waiver_required:false,
  },
  {
    id:'free-storytime-park',
    title:'Free Storytime in the Park',
    category:'kids', city:'Philadelphia',
    price_base:0, price_per_guest:0, is_free:true,
    duration_min:60,
    image:IMG('photo-1503455637927-730bce8583c0'),
    gallery:[IMG('photo-1517245386807-bb43f82c33c4')],
    description:"Free Saturday morning storytime in Rittenhouse Square. Local children's authors. Snacks provided.",
    host_name:'Philly Family Reads', host_role:'Host', host_verified:true,
    max_guests:50, min_guests:1,
    tags:['accessible'], vibes:['family','last-minute'],
    pet_friendly:true, kid_friendly:true,
    exclusive:false, points_mult:1, small_business:true,
    includes:['Story session','Snacks','Free book'],
    rating:4.9, review_count:678,
    cancellation_policy:'free',
    verification_level:'none', waiver_required:false,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COLLECTIONS (7)
// ─────────────────────────────────────────────────────────────────────────────
const COLLECTIONS = [
  {
    id:'members-only',
    title:'Reserved for Regulars and Locals',
    description:'Hand-curated experiences your status unlocks. Exclusive access for Regular and Local members.',
    badge:'MEMBERS ONLY', badge_color:'#a855f7',
    filter:(e) => e.exclusive === true,
  },
  {
    id:'free-this-week',
    title:'Free This Week',
    description:'Zero cost. All experience. Curated weekly.',
    badge:'FREE', badge_color:'#f59e0b',
    filter:(e) => e.is_free === true,
  },
  {
    id:'small-business-spotlight',
    title:'Local Business Spotlight',
    description:'Every booking directly supports a local entrepreneur.',
    badge:'LOCAL', badge_color:'#22c55e',
    filter:(e) => e.small_business === true,
  },
  {
    id:'date-night',
    title:'Date Night Picks',
    description:'Experiences that turn a night out into a memory.',
    badge:'DATE NIGHT', badge_color:'#ec4899',
    filter:(e) => e.vibes.includes('date-night'),
  },
  {
    id:'thrill-seekers',
    title:'Thrill Seekers',
    description:'For the adrenaline-curious.',
    badge:'THRILL', badge_color:'#f59e0b',
    filter:(e) => e.vibes.includes('thrill'),
  },
  {
    id:'family-time',
    title:'Family Time',
    description:'Experiences the whole family will love.',
    badge:'FAMILY', badge_color:'#3b82f6',
    filter:(e) => e.vibes.includes('family') || e.kid_friendly === true,
  },
  {
    id:'pet-welcome',
    title:'Bring Your Pet',
    description:'Experiences that welcome you to bring your pet along.',
    badge:'PET-FRIENDLY', badge_color:'#fb7185',
    filter:(e) => e.pet_friendly === true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

// Experience queries
const getByCategory      = (cat) => EXPERIENCES.filter(e => e.category === cat);
const getById            = (id)  => EXPERIENCES.find(e => e.id === id);
const getByCity          = (city)=> EXPERIENCES.filter(e => e.city === city);
const getExclusive       = ()    => EXPERIENCES.filter(e => e.exclusive);
const getFree            = ()    => EXPERIENCES.filter(e => e.is_free);
const getSmallBusiness   = ()    => EXPERIENCES.filter(e => e.small_business);
const getByVibe          = (v)   => EXPERIENCES.filter(e => e.vibes.includes(v));
const getPetFriendly     = ()    => EXPERIENCES.filter(e => e.pet_friendly);
const getKidFriendly     = ()    => EXPERIENCES.filter(e => e.kid_friendly);
const getNeedsWaiver     = ()    => EXPERIENCES.filter(e => e.waiver_required);
const getNeedsVerification = ()  => EXPERIENCES.filter(e => e.verification_level !== 'none');

// Tier preview: experiences that show as teaser to the tier below
const getPreviewsForTier = (tier) =>
  EXPERIENCES.filter(e => e.preview_for_tier === tier).slice(0, 3);

// Pricing
function calculateTotal(exp, guests, addons = []) {
  const guestFee    = Math.max(0, guests - 2) * exp.price_per_guest;
  const addonTotal  = addons.reduce((s, a) => s + a.price, 0);
  return exp.price_base + guestFee + addonTotal;
}
const isInstallmentEligible = (total) => total >= INSTALLMENT_MIN_TOTAL;

// Points — NEVER expire
function calculatePoints(exp, total, memberTier) {
  const tier = TIERS[memberTier] || TIERS.rookie;
  return Math.round(total * exp.points_mult * tier.points_mult);
}

// QE
function getQEForBooking  (price) { return getQEWeight(price); }
function calculateAnnualQE(bookings) {
  let freeQE = 0, paidQE = 0;
  for (const b of bookings) {
    const w = getQEWeight(b.price);
    if (b.price === 0) freeQE += w;
    else paidQE += w;
  }
  const total      = freeQE + paidQE;
  const maxFree    = total * FREE_QE_CAP_PCT;
  const capped     = Math.min(freeQE, maxFree);
  return Math.round((paidQE + capped) * 100) / 100;
}
function getTierForQE(qe) {
  if (qe >= TIERS.local.qe_min)   return 'local';
  if (qe >= TIERS.regular.qe_min) return 'regular';
  return 'rookie';
}

// Cancellation
function getCancellationPolicy(exp) {
  return CANCELLATION_POLICIES[exp.cancellation_policy] || CANCELLATION_POLICIES.flexible;
}

// Current rotating rewards (call with current month 0-11)
function getCurrentRotatingRewards(monthIndex) {
  const seasons = [
    'winter','winter',           // Jan, Feb
    'spring','spring','spring',  // Mar, Apr, May
    'summer','summer','summer',  // Jun, Jul, Aug
    'fall','fall','fall',        // Sep, Oct, Nov
    'winter',                    // Dec
  ];
  const season = seasons[monthIndex] || 'fall';
  return REDEMPTION_CATALOG.rotating[season] || [];
}

// Active rewards for display (3 core + 3 rotating, max 6)
function getActiveRedemptions(memberTier, monthIndex = new Date().getMonth()) {
  const tier   = memberTier || 'rookie';
  const tierOrder = ['rookie','regular','local'];
  const tierIdx   = tierOrder.indexOf(tier);
  const core    = REDEMPTION_CATALOG.core.filter(r =>
    tierOrder.indexOf(r.required_tier) <= tierIdx
  );
  const rotating = getCurrentRotatingRewards(monthIndex).filter(r =>
    tierOrder.indexOf(r.required_tier) <= tierIdx
  );
  const localOnly = tier === 'local' ? REDEMPTION_CATALOG.local_only : [];
  return [...core, ...rotating, ...localOnly].slice(0, 6);
}

// Favorites (persisted in localStorage)
function getFavoriteIds() {
  try { return JSON.parse(localStorage.getItem('wtm-favorites') || '[]'); }
  catch { return []; }
}
function toggleFavorite(experienceId) {
  const favs = getFavoriteIds();
  const idx  = favs.indexOf(experienceId);
  if (idx >= 0) favs.splice(idx, 1);
  else favs.push(experienceId);
  localStorage.setItem('wtm-favorites', JSON.stringify(favs));
  return favs.includes(experienceId);
}
function isFavorited(experienceId) { return getFavoriteIds().includes(experienceId); }
function getFavoriteExperiences()  { return EXPERIENCES.filter(e => isFavorited(e.id)); }

// ─────────────────────────────────────────────────────────────────────────────
// EXPORTS
// ─────────────────────────────────────────────────────────────────────────────
const WTM = {
  CATEGORIES, TIERS, CANCELLATION_POLICIES, VERIFICATION_LEVELS,
  POINTS, QE_WEIGHTS, FREE_QE_CAP_PCT, INSTALLMENT_MIN_TOTAL,
  ANTI_EXPLOIT, REDEMPTION_CATALOG, EXPERIENCES, COLLECTIONS,
  // queries
  getByCategory, getById, getByCity, getExclusive, getFree, getSmallBusiness,
  getByVibe, getPetFriendly, getKidFriendly, getNeedsWaiver,
  getNeedsVerification, getPreviewsForTier,
  // pricing
  calculateTotal, isInstallmentEligible, calculatePoints,
  // QE
  getQEWeight, getQEForBooking, calculateAnnualQE, getTierForQE,
  // cancellation
  getCancellationPolicy,
  // redemptions
  getCurrentRotatingRewards, getActiveRedemptions,
  // favorites
  getFavoriteIds, toggleFavorite, isFavorited, getFavoriteExperiences,
};

if (typeof window  !== 'undefined') window.WTM = WTM;
if (typeof module  !== 'undefined' && module.exports) module.exports = WTM;
